POST http://localhost:8080/alunos
Content-Type: application/json

{
  "nome": "João",
  "curso": "Informática"
}

###
POST http://localhost:8080/alunos
Content-Type: application/json

{
"nome": "Pedro",
"curso": "Node"
}
###
GET http://localhost:8080/alunos/Pedro

###
GET https://www.kabum.com.br/computadores/pc/pc-gamer?page_number=1&page_size=60&facet_filters=eyJwcmljZSI6eyJtaW4iOjI1My41LCJtYXgiOjQwMDB9fQ==&sort=most_searched
###

POST http://localhost:8080/checklist
Content-Type: application/json

{
  "curso": "João",
  "inicio": "Informática",
  "fim": "Informática",
  "compareceu": false,
  "aluno": 1
}
###
POST http://localhost:8080/alunos
Content-Type: application/json

{
"nome": "Matheus Dyzarz",
"curso": "WEB"
}

###
POST http://localhost:8080/checklist
Content-Type: application/json

{
  "descricao": "agitado",
  "horarioAula": "MANHA_10_12",
  "compareceu": false,
  "alunoId": 1}
###

GET http://localhost:8080/checklist/alunos
###

POST http://localhost:8080/checklist/filterdate
Content-Type: application/json

{
    "dataInicio": "2026-07-01",
    "dataFim": "2026-07-15"
}