POST http://localhost:8080/alunos
Content-Type: application/json

{
  "nome": "João",
  "curso": "Informática"
}

###
POST http://localhost:8080/alunos
Content-Type: application/json

{
"nome": "Meiryanne",
"curso": "Java"
}
###
GET http://localhost:8080/alunos/Pedro

###
GET https://www.kabum.com.br/computadores/pc/pc-gamer?page_number=1&page_size=60&facet_filters=eyJwcmljZSI6eyJtaW4iOjI1My41LCJtYXgiOjQwMDB9fQ==&sort=most_searched
###

POST http://localhost:8080/checklist
Content-Type: application/json

{
  "curso": "João",
  "inicio": "Informática",
  "fim": "Informática",
  "compareceu": false,
  "aluno": 1
}
###
POST http://localhost:8080/alunos
Content-Type: application/json

{
"nome": "Matheus Dyzarz",
"curso": "WEB"
}

###
POST http://localhost:8080/checklist
Content-Type: application/json

{
  "descricao": "agitado",
  "horarioAula": "MANHA_10_12",
  "compareceu": false,
  "alunoId": 1}
###

GET http://localhost:8080/checklist/alunos
###

DELETE http://localhost:8080/alunos/7
###

POST http://localhost:8080/checklist/filterdate
Content-Type: application/json

{
    "dataInicio": "2026-07-01",
    "dataFim": "2026-07-15"
}
###

GET http://localhost:8080/checklist/acompanhamento

###

PATCH http://localhost:8080/checklist/acompanhamento
Content-Type: application/json

{
  "id": 2,
  "itemConsolidado": [
    {
      "id": 8,
      "parecer": "Excelente participação.",
      "observacao": "Concluiu todas as atividades.",
      "presente": true,
      "recuperacao": false,
      "intervalo": false
    },
    {
      "id": 9,
      "parecer": "Bom desempenho.",
      "observacao": "",
      "presente": true,
      "recuperacao": false,
      "intervalo": false
    },
    {
      "id": 10,
      "parecer": "Ausente.",
      "observacao": "Faltou sem justificativa.",
      "presente": false,
      "recuperacao": false,
      "intervalo": false
    },
    {
      "id": 11,
      "parecer": "Precisa revisar o conteúdo.",
      "observacao": "Será atendida na recuperação.",
      "presente": true,
      "recuperacao": true,
      "intervalo": false
    }
  ]
}